#!/usr/bin/env bash
# =============================================================================
# perch installer. Safe to run again: every answer you gave last time is the
# default next time, and nothing is rebuilt or restarted unless it changed.
#
#   sudo ./install.sh              walk through it
#   sudo ./install.sh --yes        take the defaults, no questions
#   sudo ./install.sh --no-build   skip the container build
#   sudo ./install.sh --help
# =============================================================================
set -euo pipefail

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$INSTALL_DIR"
ENV_FILE="$INSTALL_DIR/.env"
NONINTERACTIVE=0
SKIP_BUILD=0
for a in "$@"; do
  case "$a" in
    --yes|-y) NONINTERACTIVE=1 ;;
    --no-build) SKIP_BUILD=1 ;;
    --help|-h) sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
  esac
done

if [ -t 1 ]; then B=$'\e[1m'; D=$'\e[2m'; G=$'\e[32m'; Y=$'\e[33m'; R=$'\e[31m'; C=$'\e[36m'; N=$'\e[0m'
else B=; D=; G=; Y=; R=; C=; N=; fi
say()  { printf '%s\n' "$*"; }
step() { printf '\n%s==>%s %s%s%s\n' "$C" "$N" "$B" "$*" "$N"; }
ok()   { printf '  %s✓%s %s\n' "$G" "$N" "$*"; }
warn() { printf '  %s!%s %s\n' "$Y" "$N" "$*"; }
die()  { printf '  %s✗ %s%s\n' "$R" "$*" "$N" >&2; exit 1; }
note() { printf '  %s%s%s\n' "$D" "$*" "$N"; }
have() { command -v "$1" >/dev/null 2>&1; }

ask() {
  local var="$1" prompt="$2" def="${3:-}" cur="${!1:-}" ans
  [ -n "$cur" ] && def="$cur"
  if [ "$NONINTERACTIVE" = 1 ]; then printf -v "$var" '%s' "$def"; return; fi
  if [ -n "$def" ]; then read -r -p "  $prompt [$def]: " ans || true
  else read -r -p "  $prompt: " ans || true; fi
  printf -v "$var" '%s' "${ans:-$def}"
}
ask_yn() {
  local var="$1" prompt="$2" def="${3:-y}" ans
  if [ "$NONINTERACTIVE" = 1 ]; then printf -v "$var" '%s' "$def"; return; fi
  read -r -p "  $prompt [$( [ "$def" = y ] && echo 'Y/n' || echo 'y/N')]: " ans || true
  ans="${ans:-$def}"
  case "$ans" in [Yy]*) printf -v "$var" 'y' ;; *) printf -v "$var" 'n' ;; esac
}

[ "$(id -u)" -eq 0 ] || die "run this with sudo — it installs systemd units and creates a service account."

printf '\n%s  perch%s  %sa perch for your model%s\n' "$B" "$N" "$D" "$N"

# ---------- 1. what is already here ----------
step "Checking this machine"
have podman || die "podman is not installed. On Debian/Ubuntu: apt install podman"
ok "podman $(podman --version | awk '{print $3}')"
if have podman-compose; then COMPOSE_CMD="podman-compose"
elif podman compose version >/dev/null 2>&1; then COMPOSE_CMD="podman compose"
else die "neither podman-compose nor 'podman compose' is available. On Debian/Ubuntu: apt install podman-compose"; fi
ok "using $COMPOSE_CMD"
have ssh || die "the openssh client is not installed; the tunnel needs it. apt install openssh-client"
have ssh-keygen || die "ssh-keygen is missing (openssh-client)."
ok "ssh $(ssh -V 2>&1 | awk '{print $1}')"
have systemctl || warn "no systemd here; the tunnel and the host helper will have to be run by hand."
# Not required, but worth saying: if Tor is already here, the tunnel can use
# it, and the Connect page is where that is switched on.
if ss -lnt 2>/dev/null | grep -q '127.0.0.1:9050'; then
  ok "Tor is running on 127.0.0.1:9050"
  note "the tunnel can dial out through it — Connect → advanced settings"
fi

RAM_KB=$(awk '/^MemTotal:/{print $2}' /proc/meminfo)
RAM_GB=$(( RAM_KB / 1024 / 1024 ))
ok "${RAM_GB} GB of memory, $(nproc) cores"

# ---------- 2. the GPU ----------
#
# There are two ways to give a container an NVIDIA GPU, and only one of them
# needs software installed.
#
#   CDI      the NVIDIA container toolkit generates a spec and podman hands
#            over the whole device. Tidy, and the right answer if the toolkit
#            is there.
#   devices  pass the /dev/nvidia* nodes straight through and bind-mount the
#            driver libraries over the top. The ollama image already carries
#            LD_LIBRARY_PATH=/usr/local/nvidia/lib64 for exactly this, so it
#            needs nothing installed at all.
#
# The second is written off too readily. A machine with a working driver and
# no container toolkit is a very common setup, and falling back to the CPU
# there — on a box someone bought a GPU for — is the wrong answer.

# Write a compose overlay that passes the devices and the driver libraries
# through by hand. The library filenames carry the driver version, so this has
# to be generated on the machine rather than shipped.
generate_device_overlay() {
  local out="$INSTALL_DIR/deploy/generated/compose.gpu-devices.yml"
  local libdir dev lib target found=0
  mkdir -p "$INSTALL_DIR/deploy/generated"
  libdir=$(dirname "$(ls -1 /usr/lib/*/libcuda.so.[0-9]* /usr/lib64/libcuda.so.[0-9]* 2>/dev/null | head -1)" 2>/dev/null)
  [ -n "$libdir" ] && [ -d "$libdir" ] || return 1

  {
    echo "# Generated by install.sh on $(date -Is). Do not edit; re-run the installer."
    echo "#"
    echo "# Hands the GPU to Ollama without the NVIDIA container toolkit: the device"
    echo "# nodes go through directly, and the host's driver libraries are mounted"
    echo "# where the ollama image already looks for them."
    echo "services:"
    echo "  ollama:"
    echo "    security_opt:"
    echo "      - label=disable"
    echo "    devices:"
    for dev in /dev/nvidia[0-9]* /dev/nvidiactl /dev/nvidia-modeset /dev/nvidia-uvm /dev/nvidia-uvm-tools; do
      [ -e "$dev" ] && echo "      - $dev:$dev"
    done
    echo "    volumes:"
    # soname => the name the loader actually asks for. libcuda and nvidia-ml
    # are the two that matter; the rest are needed by newer CUDA runtimes.
    for pair in "libcuda.so:1" "libnvidia-ml.so:1" "libnvidia-ptxjitcompiler.so:1" "libnvidia-nvvm.so:4" "libnvidia-cfg.so:1"; do
      lib="${pair%%:*}"; target="${pair##*:}"
      src=$(ls -1 "$libdir/$lib".[0-9]* 2>/dev/null | head -1)
      [ -n "$src" ] || continue
      echo "      - $src:/usr/local/nvidia/lib64/$lib.$target:ro"
      found=1
    done
    # libcuda.so with no soname suffix, which some builds link against.
    src=$(ls -1 "$libdir/libcuda.so".[0-9]* 2>/dev/null | head -1)
    [ -n "$src" ] && echo "      - $src:/usr/local/nvidia/lib64/libcuda.so:ro"
  } > "$out"

  [ "$found" = 1 ] || { rm -f "$out"; return 1; }
  echo "$out"
}

step "Looking for a GPU"
GPU_KIND="none"; VRAM_MB=0; GPU_MODE=""
if have nvidia-smi && nvidia-smi -L >/dev/null 2>&1; then
  GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)
  VRAM_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits | head -1)
  GPU_KIND="nvidia"
  ok "$GPU_NAME with ${VRAM_MB} MB"
  if [ -f /etc/cdi/nvidia.yaml ] || [ -f /var/run/cdi/nvidia.yaml ]; then
    GPU_MODE="cdi"
    ok "the NVIDIA container toolkit is configured"
  elif [ -e /dev/nvidiactl ] && OVERLAY=$(generate_device_overlay); then
    GPU_MODE="devices"
    ok "no container toolkit here, so passing the devices and driver libraries through directly"
    note "wrote $(basename "$OVERLAY")"
    note "if you later install the toolkit, re-run this and it will use it instead"
  else
    warn "the driver is installed but the GPU cannot be handed to a container"
    note "either install the NVIDIA container toolkit and run:"
    note "  sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml"
    note "or check that /dev/nvidia* exist and the driver libraries are readable"
    ask_yn USE_GPU_ANYWAY "Carry on with the CPU for now?" y
    [ "$USE_GPU_ANYWAY" = y ] || die "stopping so you can sort the GPU out first."
    GPU_KIND="none"
  fi
elif [ -e /dev/kfd ]; then
  GPU_KIND="amd"
  for f in /sys/class/drm/card*/device/mem_info_vram_total; do
    [ -r "$f" ] && VRAM_MB=$(( $(cat "$f") / 1048576 )) && break
  done
  ok "an AMD GPU with ${VRAM_MB} MB (ROCm)"
else
  warn "no GPU found — the model will run on the CPU, which is slow but works"
fi

# ---------- 3. sizing ----------
step "Sizing"
if [ "$VRAM_MB" -gt 1024 ]; then USABLE_MB=$(( VRAM_MB * 9 / 10 )); BASIS="the GPU"
else USABLE_MB=$(( RAM_KB / 1024 * 2 / 3 )); BASIS="system memory"; fi
# Mirrors MODELS in server/src/system.ts — keep the two in step. The
# thresholds are "needs to run well", which is the download plus room for the
# context window, not the download alone.
pick_model() {
  local mb=$1
  if   [ "$mb" -ge 25400 ]; then echo "gemma4:31b"
  elif [ "$mb" -ge 22800 ]; then echo "qwen3.8:27b"
  elif [ "$mb" -ge 10600 ]; then echo "gemma4:12b"
  elif [ "$mb" -ge 9400  ]; then echo "qwen3.5:9b"
  elif [ "$mb" -ge 5600  ]; then echo "qwen3.5:4b"
  else echo "qwen3.5:2b"; fi
}
SUGGESTED_MODEL=$(pick_model "$USABLE_MB")
note "${USABLE_MB} MB usable, judged from $BASIS"
ok "suggested model: $SUGGESTED_MODEL"
# One slot per ~6 GB of usable memory, because each slot costs a context
# window of KV cache; never fewer than one, and past four the GPU is the limit
# rather than the slot count.
SLOTS=$(( USABLE_MB / 6000 )); [ "$SLOTS" -lt 1 ] && SLOTS=1; [ "$SLOTS" -gt 4 ] && SLOTS=4
ok "$SLOTS request slot(s)"

# ---------- 4. settings ----------
step "Settings"
# shellcheck disable=SC1090
[ -f "$ENV_FILE" ] && { set -a; . "$ENV_FILE"; set +a; note "keeping what you chose last time as the defaults"; }

PERCH_STATE_DIR="${PERCH_STATE_DIR:-/var/lib/perch}"
ask PERCH_CONSOLE_PORT "Console port (on 127.0.0.1)" "${PERCH_CONSOLE_PORT:-8099}"
ask PERCH_PROXY_PORT   "Model endpoint port (on 127.0.0.1)" "${PERCH_PROXY_PORT:-11434}"
ask OLLAMA_NUM_PARALLEL "Requests answered at once" "${OLLAMA_NUM_PARALLEL:-$SLOTS}"
ask AI_MODEL "Model to download now (blank to choose later in the console)" "${AI_MODEL:-$SUGGESTED_MODEL}"

# The two optional services. Both cost memory on the same card the chat model
# is using, so they are off unless asked for, and the numbers are stated rather
# than discovered later when generation mysteriously halves in speed.
step "Optional services"
note "Both are off by default. Each is a second claim on the same GPU."
ask_yn VOICE_ENABLED "Add dictation (whisper.cpp, ~0.4-1 GB, runs fine on the CPU)?" "${VOICE_ENABLED:-n}"
if [ "$VOICE_ENABLED" = y ]; then
  # Same RAM check as the chat model: base fits anywhere, small is better on
  # accents and names.
  if [ "$RAM_GB" -ge 8 ]; then WHISPER_DEFAULT=small; else WHISPER_DEFAULT=base; fi
  ask WHISPER_MODEL "Whisper model (base or small)" "${WHISPER_MODEL:-$WHISPER_DEFAULT}"
fi
ask_yn IMAGE_ENABLED "Add image generation (Stable Diffusion, 4-10 GB on the card)?" "${IMAGE_ENABLED:-n}"
if [ "$IMAGE_ENABLED" = y ]; then
  IMAGE_NEED=4500
  if [ "$USABLE_MB" -lt $(( IMAGE_NEED + 9400 )) ]; then
    warn "this card has ${USABLE_MB} MB usable; a chat model plus Stable Diffusion wants about $(( IMAGE_NEED + 9400 )) MB"
    note "they will not both stay resident — whichever was used last will hold the card"
    note "the console's Services panel shows the running total"
  fi
fi

PERCH_SERVICES="chat"
[ "$VOICE_ENABLED" = y ] && PERCH_SERVICES="$PERCH_SERVICES,voice"
[ "$IMAGE_ENABLED" = y ] && PERCH_SERVICES="$PERCH_SERVICES,image"
ok "services: $PERCH_SERVICES"

# Every service wants a port on loopback, and a machine that already runs
# containers may well be using one. Finding that out at `up` time means a
# container that will not start and an error a long way from its cause, so the
# check happens here and moves to the next free port instead.
port_free() { ! ss -lntH 2>/dev/null | grep -q "127.0.0.1:$1 \|0.0.0.0:$1 \|\*:$1 "; }
next_free() {
  local p="$1"
  while ! port_free "$p"; do p=$(( p + 1 )); done
  printf '%s' "$p"
}
for spec in "PERCH_CONSOLE_PORT console" "PERCH_PROXY_PORT chat" "PERCH_VOICE_PORT dictation" "PERCH_IMAGE_PORT images"; do
  var="${spec%% *}"; label="${spec##* }"
  case "$label" in
    dictation) [ "$VOICE_ENABLED" = y ] || continue ;;
    images)    [ "$IMAGE_ENABLED" = y ] || continue ;;
  esac
  current="${!var}"
  if ! port_free "$current"; then
    replacement="$(next_free $(( current + 1 )))"
    warn "port $current is already in use, so $label would not start"
    note "using $replacement instead; change $var in .env if you would rather move the other thing"
    printf -v "$var" '%s' "$replacement"
  fi
done
ok "ports: console $PERCH_CONSOLE_PORT, chat $PERCH_PROXY_PORT${VOICE_ENABLED:+, dictation $PERCH_VOICE_PORT}${IMAGE_ENABLED:+, images $PERCH_IMAGE_PORT}"

COMPOSE_FILE="compose.yml"
[ "$VOICE_ENABLED" = y ] && COMPOSE_FILE="$COMPOSE_FILE:compose.voice.yml"
[ "$IMAGE_ENABLED" = y ] && COMPOSE_FILE="$COMPOSE_FILE:compose.image.yml"
case "$GPU_KIND" in
  nvidia)
    case "$GPU_MODE" in
      cdi)     COMPOSE_FILE="compose.yml:compose.gpu.yml" ;;
      devices) COMPOSE_FILE="compose.yml:deploy/generated/compose.gpu-devices.yml" ;;
    esac ;;
  amd) COMPOSE_FILE="compose.yml:compose.rocm.yml" ;;
esac
ok "compose overlays: $COMPOSE_FILE"

# ---------- 5. the service account ----------
step "The tunnel account on this machine"
# The tunnel runs unprivileged. Only this account can read the key.
if id perch >/dev/null 2>&1; then
  ok "the perch account already exists"
else
  useradd --system --no-create-home --home-dir "$PERCH_STATE_DIR" --shell /usr/sbin/nologin perch 2>/dev/null \
    || useradd --system --no-create-home --home-dir "$PERCH_STATE_DIR" --shell /sbin/nologin perch
  ok "created the perch account (no shell, no password)"
fi

# ---------- 6. the state directory ----------
step "State"
# 711, not 750. Three different identities need to reach into this directory:
# the console container (uid 1000, the owner), the host helper (root), and the
# unprivileged account the tunnel runs as — which is none of those and cannot
# traverse a 750 directory owned by somebody else. It failed as "Identity file
# not accessible", which reads like a missing key rather than a missing +x.
install -d -m 711 "$PERCH_STATE_DIR"
# 711: the tunnel account owns the private keys and only it can read them,
# but the console container (a different uid) must be able to traverse here to
# read a public key back. See do_keygen in deploy/perch-hostd.
install -d -m 711 "$PERCH_STATE_DIR/ssh"
install -d -m 755 "$PERCH_STATE_DIR/host"
install -d -m 733 "$PERCH_STATE_DIR/host/requests"
install -d -m 755 "$PERCH_STATE_DIR/host/results"
# The container runs as uid 1000; the host helper runs as root. Both need the
# directory, so it belongs to 1000 with the perch account's group.
chown -R 1000:1000 "$PERCH_STATE_DIR" 2>/dev/null || true
chown -R perch "$PERCH_STATE_DIR/ssh" 2>/dev/null || true
ok "$PERCH_STATE_DIR"

# ---------- 7. .env ----------
step "Writing .env"
cat > "$ENV_FILE" <<EOF
# Written by install.sh. Run it again to change any of this; it keeps your
# answers as the defaults.

# Where the console and the model endpoint listen. Both on 127.0.0.1 — the
# tunnel picks the endpoint up from there, and nothing needs a router change.
PERCH_CONSOLE_PORT=$PERCH_CONSOLE_PORT
PERCH_PROXY_PORT=$PERCH_PROXY_PORT
PERCH_STATE_DIR=$PERCH_STATE_DIR
PERCH_MAX_CONCURRENT=$(( OLLAMA_NUM_PARALLEL + 2 ))
# Which endpoints listen at all. A machine that only writes email should not
# have an image generator on a port.
PERCH_SERVICES=$PERCH_SERVICES
PERCH_VOICE_PORT=${PERCH_VOICE_PORT:-11435}
PERCH_IMAGE_PORT=${PERCH_IMAGE_PORT:-11436}
WHISPER_MODEL=${WHISPER_MODEL:-base}
PERCH_LOG_LEVEL=info
PERCH_VERSION=0.1.0

# Ollama. These are read when it starts, so change them here (or in the
# console) and restart.
OLLAMA_NUM_PARALLEL=$OLLAMA_NUM_PARALLEL
OLLAMA_MAX_LOADED_MODELS=1
OLLAMA_FLASH_ATTENTION=1
OLLAMA_KV_CACHE_TYPE=q8_0
OLLAMA_MAX_QUEUE=32
OLLAMA_KEEP_ALIVE=10m

# The model install.sh downloaded, for reference. The console is where you
# change which one is in use.
AI_MODEL=$AI_MODEL

# Compose overlays, colon separated.
COMPOSE_FILE=$COMPOSE_FILE
EOF
chmod 600 "$ENV_FILE"
ok "$ENV_FILE"

# ---------- 8. systemd ----------
step "systemd units"
render() {
  sed -e "s|__PERCH_DIR__|$INSTALL_DIR|g" -e "s|__STATE_DIR__|$PERCH_STATE_DIR|g" \
      -e "s|__PERCH_UID__|1000|g" -e "s|__PERCH_GID__|1000|g" "$1" > "$2"
  chmod 644 "$2"
}
if have systemctl; then
  render deploy/perch-hostd.service.tmpl /etc/systemd/system/perch-hostd.service
  render deploy/perch.service.tmpl /etc/systemd/system/perch.service
  systemctl daemon-reload
  systemctl enable --now perch-hostd.service >/dev/null 2>&1 && ok "perch-hostd is running" \
    || warn "perch-hostd did not start; see: journalctl -u perch-hostd"
  ask_yn BOOT "Start perch when this machine boots?" y
  if [ "$BOOT" = y ]; then systemctl enable perch.service >/dev/null 2>&1 && ok "it will start at boot"
  else systemctl disable perch.service >/dev/null 2>&1 || true; note "it will not start at boot"; fi
else
  warn "no systemd; skipping the host helper and the boot unit"
fi

# ---------- 9. build and start ----------
step "Containers"
export COMPOSE_FILE
compose() { $COMPOSE_CMD --env-file "$ENV_FILE" "$@"; }
if [ "$SKIP_BUILD" = 0 ]; then
  note "building the perch image (a minute or two the first time)"
  compose build perch >/dev/null || die "the build failed. Run: $COMPOSE_CMD build perch"
  ok "image built"
fi
compose up -d || die "could not start the containers. Run: $COMPOSE_CMD up -d"
ok "containers started"

printf '  waiting for perch to answer'
for _ in $(seq 1 30); do
  if curl -fsS --max-time 2 "http://127.0.0.1:$PERCH_PROXY_PORT/healthz" >/dev/null 2>&1; then READY=1; break; fi
  printf '.'; sleep 1
done
printf '\n'
[ "${READY:-0}" = 1 ] && ok "perch is up" || warn "perch is not answering yet; check ./bin/perch logs perch"

# ---------- 10. the model ----------
if [ -n "$AI_MODEL" ]; then
  step "Downloading $AI_MODEL"
  note "this is a few gigabytes and takes as long as your line takes"
  compose exec -T ollama ollama pull "$AI_MODEL" || warn "the download did not finish; you can retry from the console"
fi

# ---------- 11. a token ----------
step "A token for Tern"
TOKEN_JSON=$(curl -fsS --max-time 10 -X POST "http://127.0.0.1:$PERCH_CONSOLE_PORT/api/tokens" \
  -H 'Content-Type: application/json' -d '{"name":"Tern","scopes":["use","manage"]}' 2>/dev/null || true)
TOKEN=$(printf '%s' "$TOKEN_JSON" | sed -n 's/.*"token":"\([^"]*\)".*/\1/p')

cat <<EOF

$B  perch is installed.$N

  Console        ${C}http://127.0.0.1:$PERCH_CONSOLE_PORT${N}
  Model endpoint 127.0.0.1:$PERCH_PROXY_PORT  ${D}(loopback only, for the tunnel)${N}
EOF
if [ -n "$TOKEN" ]; then
  cat <<EOF

  A token for Tern — copy it now, it is not shown again:

    ${C}$TOKEN${N}
EOF
else
  note "make a token in the console under Settings."
fi
cat <<EOF

  ${B}Next:${N} open the console and go to ${B}Connect${N}. It walks through
  generating a key, authorising it on the box Tern runs on, starting the
  tunnel, and gives you the two settings Tern needs.

  ${D}./bin/perch help   for everything you can do from a terminal${D}${N}

EOF
